# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160930_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_connection',
        ),
    ]
