# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_utilisateur_last_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='hruid',
        ),
    ]
