# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_utilisateur_hruid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='titre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='trigramme',
            field=models.CharField(default='', max_length=3),
        ),
    ]
