# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161002_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='titre',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='trigramme',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
