# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161004_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='user',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
