# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161111_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='text',
            field=tinymce.models.HTMLField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titre'),
        ),
    ]
