# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20161111_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='work',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
