# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170216_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
    ]
